# Generated by Django 5.2.1 on 2025-05-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['order', 'start_date', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['name', 'start_date']},
        ),
        migrations.RemoveField(
            model_name='journey',
            name='date',
        ),
        migrations.AddField(
            model_name='journey',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journey',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('train', 'Train'), ('plane', 'Plane'), ('bus', 'Bus'), ('bicycle', 'Bicycle'), ('ferry', 'Ferry'), ('walk', 'Walk'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
