# Generated by Django 5.2.1 on 2025-05-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_journey_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='to_location',
        ),
        migrations.AddField(
            model_name='journey',
            name='from_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='from_location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='from_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='to_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='to_location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='to_location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('walk', 'Walk'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('ferry', 'Ferry'), ('plane', 'Plane')], max_length=50, null=True),
        ),
    ]
